# Generated by Django 4.0.1 on 2022-01-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('iso_code', models.CharField(max_length=3, verbose_name='Код ISO 4217')),
                ('symbol', models.CharField(max_length=1, verbose_name='Символ')),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
