# Generated by Django 4.0.1 on 2022-01-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Биржа',
                'verbose_name_plural': 'Биржи',
                'db_table': 'stock_exchange',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('name',), 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
    ]
