# Generated by Django 4.0.1 on 2022-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_stockexchange_alter_currency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Группа стран',
                'verbose_name_plural': 'Группы стран',
                'db_table': 'country_group',
                'ordering': ('name',),
            },
        ),
    ]
