# Generated by Django 4.0.1 on 2022-01-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_bondtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид акций',
                'verbose_name_plural': 'Виды акций',
                'db_table': 'share_type',
                'ordering': ('name',),
            },
        ),
    ]
