# Generated by Django 4.0.1 on 2022-01-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_etftype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Управляющая компания',
                'verbose_name_plural': 'Управляющие компании',
                'db_table': 'management_company',
                'ordering': ('name',),
            },
        ),
    ]
