# Generated by Django 4.0.1 on 2022-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_managementcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип актива',
                'verbose_name_plural': 'Типы актива',
                'db_table': 'asset_type',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='BondType',
        ),
        migrations.DeleteModel(
            name='EtfType',
        ),
        migrations.DeleteModel(
            name='ShareType',
        ),
    ]
