# Generated by Django 4.0.1 on 2022-01-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_assettype_delete_bondtype_delete_etftype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assettype', verbose_name='Тип актива')),
            ],
            options={
                'verbose_name': 'Подтип актива',
                'verbose_name_plural': 'Подтипы актива',
                'db_table': 'asset_subtype',
                'ordering': ('name',),
            },
        ),
    ]
